# Generated by Django 4.1 on 2024-04-13 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kakao",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("nickname", models.TextField(max_length=100)),
            ],
            options={
                "db_table": "kakao",
            },
        ),
        migrations.CreateModel(
            name="KakaoToken",
            fields=[
                (
                    "token",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="kakao.kakao"
                    ),
                ),
            ],
            options={
                "db_table": "kakao_token",
            },
        ),
    ]
