# Generated by Django 4.1 on 2024-04-15 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("kakao", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "custom_id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("title", models.TextField(max_length=100)),
                ("content", models.TextField(max_length=1000)),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("modification_time", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="kakao.kakao"
                    ),
                ),
            ],
            options={
                "db_table": "board",
            },
        ),
    ]
